# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facility Name')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FACILITY',
                'verbose_name_plural': 'FACILITIES',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Hcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(blank=True, max_length=255, null=True, verbose_name='Member Name')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HCC',
                'verbose_name_plural': 'HCCs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Nhcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative', models.CharField(blank=True, max_length=255, null=True, verbose_name='Member Name')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Position')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NHCS',
                'verbose_name_plural': 'NHCSs',
                'ordering': ['-created'],
            },
        ),
    ]
